### ISSUE TITLE
点食材包会报错，然后就自动开始下载客户端apk

### ISSUE THREAD

**Issue by qiuyuluuu** [leonyan18/chief#1]
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
/blackboard/activity-yeGIPr7OX.html?from=native&share_medium=android&share_plat=android&share_source=QQ&share_tag=s_i&timestamp=1612692228&unique_k=EFDQTP#/:1

Failed to launch 'bilibili://browser?url=https%3A%2F%2Fwww.bilibili.com%2Fblackboard%2Factivity-yeGIPr7OX.html%3Ffrom%3Dnative%26share_medium%3Dandroid%26share_plat%3Dandroid%26share_source%3DQQ%26share_tag%3Ds_i%26timestamp%3D1612692228%26unique_k%3DEFDQTP%23%2F&' because the scheme does not have a registered handler.
1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18 

Resource interpreted as Document but transferred with MIME type application/vnd.android.package-archive: "https://dl.hdslb.com/mobile/latest/iBiliPlayer-html5_share_source_qqchat.apk".
(anonymous) @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
setTimeout (async)
(anonymous) @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
i @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
p @ spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:1
value @ 2.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:1
!click @ 2.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:1
qt @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:7
n @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:7
Gr.o._wrapper @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:7

**Comment by leonyan18** [comment]
可以不点食材包，直接点烹制，里面会有请求获得核心配料和辅料的。

**Comment by leonyan18** [comment]
> DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> /blackboard/activity-yeGIPr7OX.html?from=native&share_medium=android&share_plat=android&share_source=QQ&share_tag=s_i&timestamp=1612692228&unique_k=EFDQTP#/:1
> 
> Failed to launch 'bilibili://browser?url=https%3A%2F%2Fwww.bilibili.com%2Fblackboard%2Factivity-yeGIPr7OX.html%3Ffrom%3Dnative%26share_medium%3Dandroid%26share_plat%3Dandroid%26share_source%3DQQ%26share_tag%3Ds_i%26timestamp%3D1612692228%26unique_k%3DEFDQTP%23%2F&' because the scheme does not have a registered handler.
> 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
> 
> Resource interpreted as Document but transferred with MIME type application/vnd.android.package-archive: "https://dl.hdslb.com/mobile/latest/iBiliPlayer-html5_share_source_qqchat.apk".
> (anonymous) @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
> setTimeout (async)
> (anonymous) @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
> i @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:18
> p @ spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:1
> value @ 2.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:1
> !click @ 2.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:1
> qt @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:7
> n @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:7
> Gr.o._wrapper @ 1.spring-2021.a1b21c20cc63d89c0607ae71a89bd4a7c03da8ca.js:7

可以不点食材包，直接点烹制，里面会有请求获得核心配料和辅料的。
